baseURL = 'https://kausm.in/'
languageCode = 'en-us'
title = 'Kaustubh M.'
theme="PaperMod"

[params]

  ShowFullTextInRSS = true

  [params.homeInfoParams]
  Title = "Kaustubh Maske Patil"
  Content = """\
    20 | Software developer. Amateur chess player. Never went to a college.

    Interests: <i>Python, Haskell, Programming Languages, Functional Programming, Machine Learning, self-hosting</i>

    Projects: <a target="_blank" href="https://github.com/nikochiko/autosaved">autosaved</a>, \
              <a target="_blank" href="https://github.com/nikochiko/metapy">metapy</a>, \
              <a target="_blank" href="https://github.com/pipalacademy/kutty">kutty (at work)</a>

    <a href="/about-me">More about me...</a>
    """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nikochiko"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/n1kochiko"

  [[params.socialIcons]]
  name = "lichess"
  url = "https://lichess.org/@/kaustico"

[markup.goldmark.renderer]
unsafe = true
