baseURL = 'https://kausm.in/'
languageCode = 'en-us'
title = 'Kaustubh M.'
theme="PaperMod"

[params]

  ShowFullTextInRSS = true

  [params.homeInfoParams]
  Title = "Kaustubh Maske Patil"
  Content = """\
    20 | Software developer. Amateur chess player. Never went to a college.

    I contribute to and build FOSS for fun, and ocassionally write about programming.
    My current interest is in the design and implementation of programming languages.

    I have a broad skill set that is still expanding. I have good experience in web development,
    infra, Python, Linux, and machine learning. I am currently learning more about programming
    languages, compilers and interpreters, and Haskell.

    <a href="/about-me">More about me...</a>
    """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nikochiko"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/n1kochiko"

  [[params.socialIcons]]
  name = "lichess"
  url = "https://lichess.org/@/kaustico"

[markup.goldmark.renderer]
unsafe = true
